### ISSUE TITLE
What node can do the scaling (thinking of AdcScale in Ephys library)?

### ISSUE THREAD

**Issue by ChucklesOnGitHub** [open-ephys/bonsai-onix1-docs#124]

**Comment by ChucklesOnGitHub** [comment]
![image](https://github.com/user-attachments/assets/abd2e27d-63d4-47b6-9373-bc2953468ced)

ConvertScale will do. See above for hs-64 amplifier data. We'd have to specify the scale and offset for each device that produces Mat data in our headstages.

**Comment by ChucklesOnGitHub** [comment]
Actually, the convert scale offset needs to be multiplied by the gain. It works differently from the Ephys socket. Be explicit about the calculation in the tutorial

**Comment by cjsha** [comment]
If you want the calculation to be more simple, although more verbose, it's worth considering putting two `ConvertScale` nodes. The first one does the -512 offset, and the second one does the 0.195 multiplication.

There's also this 3rd option, but it's probably not even worth mentioning. It avoids adding a second `ConvertScale` node, but ends up adding a whole bunch of crap in the process. [testing.zip](https://github.com/user-attachments/files/17578060/testing.zip) It's a zip because github doesn't support uploading bonsai files directly.
