### ISSUE TITLE
Remove Heartbeat from Breakout Board Example Workflow

### ISSUE THREAD

**Issue by cjsha** [open-ephys/bonsai-onix1-docs#94]
Heartbeat is a watchdog that can be used to make sure the breakout board processes are not being blocked. This is too in-depth for a quick-start example workflow which the example workflow is supposed to be?

If we're going to keep it, we should at least do a better job of explaining its utility and/or use it in a way that is more helpful to the user.

**Comment by jonnew** [comment]
I would leave this in the user guide and example workflow, as is. I would then state, that its not being recorded in anyway because  hardware communicating is 'blocking', meaning that if no data is produced by the hardware (e.g. if no data sources are enabled), the software could wait forever to get data. The heartbeat **should not** be able to  be disabled and therefore prevents blocking forever in the case that no other data sources are enabled. 

Related:

https://github.com/open-ephys/bonsai-onix1/issues/352
